apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
 type: LoadBalancer
 ports:
  - targetPort: 5000
    port: 5000
    nodePort: 30000
 selector:
  app: api_gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  selector:
    matchLabels:
      app: api_gateway
  replicas: 3
  template:
    metadata:
      labels:
        app: api_gateway
    spec:
      containers:
      - name: api-gateway
        imagePullPolicy: Always
        image: vishalp04/user_management:latest
        ports:
        - containerPort: 5000
