apiVersion: v1
kind: Service
metadata:
  name: user-management
spec:
 type: LoadBalancer
 ports:
  - targetPort: 80
    port: 80
    nodePort: 30080
 selector:
  app: usermanagement
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermanagement
spec:
  selector:
    matchLabels:
      app: usermanagement
  replicas: 3
  template:
    metadata:
      labels:
        app: usermanagement
    spec:
      containers:
      - name: user-management
        imagePullPolicy: Always
        image: iuwitcher2020/dockerized_user_management:latest
        ports:
        - containerPort: 80
