apiVersion: v1
kind: Service
metadata:
  name: user-management
spec:
 type: LoadBalancer
 ports:
  - targetPort: 5000
    port: 5000
    nodePort: 30000
 selector:
  app: user_management
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user_management
spec:
  selector:
    matchLabels:
      app: user_management
  replicas: 3
  template:
    metadata:
      labels:
        app: user_management
    spec:
      containers:
      - name: user-management
        imagePullPolicy: Always
        image: vishalp04/user_management:latest
        ports:
        - containerPort: 5000
