apiVersion: v1
kind: Service
metadata:
  name: data-retrieval
spec:
 type: LoadBalancer
 ports:
  - targetPort: 5001
    port: 5001
    nodePort: 30001
 selector:
  app: data_retrieval
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-retrieval
spec:
  selector:
    matchLabels:
      app: data_retrieval
  replicas: 3
  template:
    metadata:
      labels:
        app: data_retrieval
    spec:
      containers:
      - name: data-retrieval
        imagePullPolicy: Always
        image: iuwitcher2020/dockerized_data_retrieval
        ports:
        - containerPort: 5001
