apiVersion: apps/v1
kind: Pod
metadata:
    name: db
    labels:
        name: mongo
        app: witcherapp
spec:
    containers:
        - image: mongo
          name: mongo
          ports:
              - name: mongo
                containerPort: 27017
          volumeMounts:
              - name: witcher-mongo-storage
                mountPath: /data/db
    volumes:
        - name: witcher-mongo-storage
          hostPath:
              path: /data/db
---
apiVersion: v1
kind: Service
metadata:
    name: db
    labels:
        name: mongo
        app: witcherapp
spec:
    selector:
        name: mongo
    type: ClusterIP
    ports:
        - name: db
          port: 27017
          targetPort: 27017