version: '3'

services:

    rabbit:
      hostname: rabbit
      image: rabbitmq
      ports:
        - "5674:5672"  # we forward this port because it's useful for debugging
        - "15674:15672"  # here, we can access rabbitmq management plugin

    post_proc :
      build : "./post-processing"
      hostname : post_proc
      image : post_proc_image
      ports :
        - "5004:5004"
      depends_on :
        - rabbit

    model_exec :
      build : "./model-execution"
      hostname : model_exec
      image : model_exec_image
      ports :
        - "5003:5003"
      depends_on :
        - rabbit

    data_retrv :
      build : "./data-retrieval"
      hostname : data_retrv
      image : data_retrv_image
      ports :
        - "5002:5002"
      depends_on :
        - rabbit

    api_gate :
      build : "./api-gateway"
      hostname : api_gate
      image : api_gate_way
      ports :
        - "5000:5000"
      depends_on :
        - rabbit
      links :
        - "php_web:phpserver"


    react_ui :
      build : "./ui"
      hostname : react_ui
      image : react_ui
      ports :
        - "3000:3000"
      links :
        - "api_gate:apigateway"

    php_web:
      image: php:7.2.2-apache
      container_name: php_web
      hostname : php_web
      depends_on:
        - db
      volumes:
        - ./lamp-stack/php/:/var/www/html/
      ports:
        - "8100:80"
      stdin_open: true
      tty: true

    db:
      image: mysql:5.7
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: test_db
        MYSQL_USER: devuser
        MYSQL_PASSWORD: devpass
      ports:
        - "9906:3306"
    session_man:
        container_name: session-management
        restart: always
        build: .
        ports:
            - '4321:4321'
        depends_on:
            - mongo
        
    mongo:
        container_name: mongo
        image: mongo
        ports:
            - '27017:27017'
