#apiVersion: extensions/v1beta1
apiVersion: v1
kind: ReplicaSet
metadata:
  name: post-processing
  labels:
    name: post-processing
    app: todoapp

spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: post-processing
    spec:
      containers:
      - name: post-processing
        image: iuwitcher2020/dockerized_post_processing
        ports:
        - containerPort: 3002
