apiVersion: v1
kind: Service
metadata:
  name: post-processing
spec:
 type: LoadBalancer
 ports:
  - targetPort: 5003
    port: 5003
    nodePort: 30003
 selector:
  app: python
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-processing
spec:
  selector:
    matchLabels:
      app: python
  replicas: 3
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: post-processing
        imagePullPolicy: Always
        image: iuwitcher2020/dockerized_model_execution
        ports:
        - containerPort: 5003
