apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  labels:
    name: api-gateway
    app: todoapp

spec:
  selector:
    name: api-gateway

  type: NodePort
  ports:
    - name: api-gateway
      port: 5000
      targetPort: 5000
