version: '3'

services:

  # RabbitMQ
    rabbit:
      build : "./message-broker"
      hostname: rabbit
      image: rabbitmq:3
      ports:
        - "5672:5672"  # we forward this port because it's useful for debugging
        - "15672:15672"  # here, we can access rabbitmq management plugin

  prim_send :
    build : "./primary-sender"
    hostname : prim_send
    image : data_retrv_image
    ports :
      - "5000"
    links : [ "rabbit" ]

  # data_retrv :
  #   build : "./data-retrieval"
  #   hostname : data_retrv
  #   image : data_retrv_image
  #   ports :
  #     - "5001"
  #   links : [ "rabbit" ]
  #
  # model_exec :
  #   build : "./model-execution"
  #   hostname : model_exec
  #   image : model_exec_image
  #   ports :
  #     - "5002"
  #   links : [ "rabbit" ]
  #
  # post_proc :
  #   build : "./post-processing"
  #   hostname : post_proc
  #   image : post_proc_image
  #   ports :
  #     - "5003"
  #
  # final_recv :
  #   build : "./final-reciever"
  #   hostname : final_recv
  #   image : final_recv_image
  #   ports :
  #     - "5004"

  #   links: ["rabbit"]
  # #Data Processing WS
  # web:
  #  build: .
  #  # command: python manage.py runserver 0.0.0.0:9060 --noreload
  #   volumes:
  #     - .:/srv
  #  ports:
  #     - "9060:9060"
  #   links: ["rabbit"]
