version: '3'
services:
    app:
        container_name: ads-session-management
        restart: always
        build: .
        ports:
            - '4321:4321'
        links:
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        ports:
            - '27017:27017'