language: python
python: 3.7
sudo: false

services:
  - docker

script:
  - echo "Model Execution"

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO = model_execution
  - docker build -t model_execution:latest .
  - docker push model_execution:latest
