apiVersion: v1
kind: Service
metadata:
  name: message-broker
spec:
 type: LoadBalancer
 ports:
  - targetPort: 5672
    port: 5672
    nodePort: 35672
 selector:
  app: message_broker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-broker
spec:
  selector:
    matchLabels:
      app: message_broker
  replicas: 3
  template:
    metadata:
      labels:
        app: message-broker
    spec:
      containers:
      - name: message-broker
        imagePullPolicy: Always
        image: iuwitcher2020/dockerized_message_broker
        ports:
        - containerPort: 5672
