apiVersion: v1
kind: Service
metadata:
  name: model-execution
  labels:
    name: model-execution
    app: todoapp

spec:
  selector:
    name: model-execution

  type: ClusterIP
  ports:
    - name: db
      port: 5002
      targetPort: 5002
