language: python
python: 3.7
sudo: false

services:
  - docker

script:
  - echo "Data Retrival"

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO = data_retrival
  - docker build -t data_retrival:latest .
  - docker push data_retrival:latest
