apiVersion: v1
kind: Service
metadata:
  name: ui
spec:
 type: LoadBalancer
 ports:
  - targetPort: 3000
    port: 3000
    nodePort: 30030
 selector:
  app: ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
spec:
  selector:
    matchLabels:
      app: ui
  replicas: 1
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        imagePullPolicy: Always
        image: iuwitcher2020/dockerized_ui_v1:latest
        ports:
        - containerPort: 3000
